Numpy : Practice Problem

1. Extract all odd numbers from arr


In [7]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [8]:
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

2. Replace all odd numbers in arr with -1

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[arr%2!=0]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

3. Convert a 1D array to a 2D array with 2 rows

In [10]:
arr=np.arange(10)
arr.reshape(2,-1)



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

4. Stack arrays a and b vertically

In [11]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [12]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

5. Get all items between 5 and 10 from a

In [26]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>=6)&(a<=10)]


array([ 6,  9, 10])

Desired Output:
(array([6, 9, 10]),)

6. Create a null vector of size 10 but the fifth value which is 1.

In [27]:
null=np.zeros(10,int)
null[4]=1
null

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

7. Create a vector with values ranging from 10 to 49.

In [28]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Create a 10x10 array with random values and find the minimum and maximum values.

In [29]:
ran=np.random.randint(1,1000,(10,10))
print(ran)
print('Maximum value is %u'%ran.max())
print('Minimum value is %u'%ran.min())

[[982 769 299 363 468 757 455 156  33 666]
 [222 149 197 515 465 201 962 404 535 635]
 [474 885 714 605 575 479 349 319 958 925]
 [338 750 642  44 705 321 923 449 236 498]
 [406 465 672 277 878 928 489 626 114 205]
 [533 565 542 955  63 305 706 813 579 217]
 [326 498 908 499 281  36 971 184 381 589]
 [467 809 483 343  64 877 199 456 824 200]
 [534 126 104 699 897 456 256 266 496  73]
 [477 731 771  90 152 593 711 683 162 528]]
Maximum value is 982
Minimum value is 33


9. Create a 3*3 matrix and print it's transpose matrix

In [30]:
np.random.seed(0)
tran=np.random.randint(1,10,(3,3))
print(tran)
np.transpose(tran)

[[6 1 4]
 [4 8 4]
 [6 3 5]]


array([[6, 4, 6],
       [1, 8, 3],
       [4, 4, 5]])

10. Create two arrays of 2-D and find dot product of it.

In [32]:
np.random.seed(0)
a=np.random.randint(1,10,(2,2))
b=np.random.randint(1,10,(2,2))
print(a)
print(b)
np.dot(a,b)

[[6 1]
 [4 4]]
[[8 4]
 [6 3]]


array([[54, 27],
       [56, 28]])

11. Compute the maximum for each row in the given array.

In [36]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)
a.max(axis=1)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]


array([9, 8, 6, 3, 9])

12. Select 3rd & 5th row and 3rd & 4th columns

In [37]:
data = np.random.randint(10,100,(5,4))
data

array([[25, 70, 68, 26],
       [19, 96, 12, 37],
       [14, 41, 11, 23],
       [93, 14, 69, 77],
       [17, 59, 57, 75]])

In [38]:
print(data[[2,4],:])
print(data[:,[2,3]])

[[14 41 11 23]
 [17 59 57 75]]
[[68 26]
 [12 37]
 [11 23]
 [69 77]
 [57 75]]


13. Convert below matrix into vector

In [40]:
matrix = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

In [41]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

14. The product of two inverse matrix is identical matrix,prove

In [52]:
# create a square matrix
m = np.array([[2,3],
              [2,4]])

a=np.linalg.inv(m)
a**2

array([[4.  , 2.25],
       [1.  , 1.  ]])

15. Create a matrix from a uniform distribution over [0, 1)

In [44]:
a=np.random.rand(2,2)

In [45]:
a

array([[0.56874553, 0.17862432],
       [0.5325737 , 0.64669147]])